version: "3.3"
services:
  apache:
    image: php-web:7.4-apache
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 3000M
      restart_policy:
        condition: on-failure
    configs:
      - source: apache_config
        target: /etc/apache2/apache2.conf
      - source: php_production_config
        target: /usr/local/etc/php/php.ini-production
      - source: php_development_config
        target: /usr/local/etc/php/php.ini-development
        # se debe definir cual es el archivo que se va a montar en la configuracion por defecto
      - source: php_development_config
        target: /usr/local/etc/php/php.ini
    volumes:
      - ./volumes/html/web:/var/www/html
      #- ./volumes/logs/logs_apache:/var/log/apache2
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host:web.localhost.com"
      - "traefik.port=80"
      - "traefik.docker.network=local_net_docker"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

configs:
  apache_config:
    file: ./sources/config/apache/apache2.conf
  php_production_config:
    file: ./sources/config/apache/php.ini-production
  php_development_config:
    file: ./sources/config/apache/php.ini-development

networks:
  default:
    external:
      name: local_net_docker
